packages:
  - "app"
  - "tools"
  - "tests"
  - "packages/snap"
  - "server/prisma"
  - "packages/node"
  - "packages/github"
  - "packages/vscode"
  - "packages/cli"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
